---
title: "FunctionalKPg"
output: html_document
date: "2026-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{R}
#install necessary packages
if (!require(rstudioapi)){install.packages("rstudioapi")}
me <- (rstudioapi::getActiveDocumentContext()$path) #get current file name
wd <- dirname(me)

if (!require(renv)){ install.packages("renv")}

#because I use an old version of iNEXT
if(!require(iNEXT)){remotes::install_version("iNEXT", version = "2.0.20")}

packs <- unique(renv::dependencies(me)$Package) #list of packages needed 

for (i in seq_along(packs)){
  if (!require(packs[i], character.only=T)){ #install any missing pacls
    install.packages(packs[i])
  }
}

lapply(packs, library, character.only=T) #load packages

rm(me, packs, i) #clean env

```


## Import Data

```{r}
load(paste0(wd, "/Data/comp_dat.RData")) #load in working data
load(paste0(wd, "/Data/align_dat.RData")) #load in data with time alignments
load(paste0(wd, "/Data/d18O_ref.RData")) #d18O reference sets

```


## Separate into strat sections and plot by section

```{r}
#make separate dataset for each section
sect_data <- list()
sections <- unique(wk_data$Section)

for (i in seq_along(sections)){
  name <- sections[[i]]
  dat <- filter(wk_data, Section == name)
  sect_data[[name]] <- dat
}



rm(i, dat, name)
```

```{r}
#plot each section 
library(ggplot2)
plots <- list()

for (i in seq_along(sect_data)){
  dat <- sect_data[[i]]
  name <- paste0(dat$Section[1]) #give it the name of the section
  
  d13C <- dat$d.13C.12C..VPDB
  meter <- dat$meter
  
  p <- ggplot(data = dat, aes(x = meter, y = d13C)) +
    theme_classic() +
    geom_point(color = "#8d58b8", shape = 2) +
    coord_flip() +
    geom_smooth(color = "#463c82", fill = "#c1bae8") +
    labs(y = "d13C", x = "meter", title = name)
  
  plots[[name]] <- p
    
}

```

```{r}
#d13C plots
dat <- wk_data
d13C <- dat$d13C
d18O <- dat$d18O
meter <- dat$meter

p_d13C <- ggplot(data = dat, aes(x = meter, y = d13C)) +
    theme_bw() +
    geom_point(color = "#4b8c3c", shape = 2) + #add point data
    ylim((min(d13C)-0.01), (max(d13C)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
  
    geom_smooth(color = "#17400d", fill = "#aecca7") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "d13C", 
         x = "meter", 
         title = "d13C Plots",
         caption = "K-Pg Boundary at 0 m") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
    

plot(p_d13C)

setwd(paste0(wd, "/Figures"))
ggsave("p_d13C.png", width = 10, height = 6)
setwd(wd)

#plot d18O
p_d18O <- ggplot(data = dat, aes(x = meter, y = d18O)) +
    theme_bw() +
    geom_point(color = "#346aa3", shape = 2) + #add point data
    ylim((min(d18O)-0.01), (max(d18O)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
  
    geom_smooth(color = "#103a66", fill = "#b1c7de") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "d18O", 
         x = "meter", 
         title = "d18O Plots",
         caption = "K-Pg Boundary at 0 m") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
    

plot(p_d18O)


setwd(paste0(wd, "/Figures"))
ggsave("p_d18O.png", width = 10, height = 6)
setwd(wd)
```

# Temperatures from d18O 
```{r}
#calculate temperatures given d18O data
library(isogeochem)

#use function isogeochem::temp_d18O(d18O_c_VSMOW, d18O_H2O_VSMOW, min, eq))
#d18O_c_VSMOW	= Carbonate d18O value expressed on the VSMOW scale (‰).
#d18O_H2O_VSMOW	= Water d18O value expressed on the VSMOW scale (‰).
#min = mineralogy; Options are "calcite", "aragonite", "apatite", "siderite", and "dolomite".
#eq = "ONeil69"

#add column to data with VSMOW d18O (from VPDB)
wk_data$d18O_VSMOW <- to_VSMOW(wk_data$d18O)
H2O_VSMOW <- to_VSMOW(0)

#add column calculating temps (deg C)
wk_data$Temp_0 <- temp_d18O(wk_data$d18O_VSMOW, 0, "calcite", "ONeil69")
wk_data$Temp_min1 <- temp_d18O(wk_data$d18O_VSMOW, -1, "calcite", "ONeil69")
```

##Plot Temperature Data
```{r}
#plot Temp given water d18O value = 0 (VSMOW)
library(ggplot2)
p_Temp_0 <- ggplot(data = wk_data, aes(x = meter, y = Temp_0)) +
    theme_bw() +
    geom_point(color = "#8d58b8", shape = 2) + #add point data
    ylim((min(wk_data$Temp_0)-0.01), (max(wk_data$Temp_0)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
  
    geom_smooth(color = "#463c82", fill = "#c1bae8") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "Temperature (deg C)", 
         x = "meter", 
         title = "Temperature Plots",
         caption = "K-Pg Boundary at 0 m") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
plot(p_Temp_0)


setwd(paste0(wd, "/Figures"))
ggsave("p_Temp_0.png", width = 10, height = 6)
setwd(wd)

#plot Temperature (given water d18O value = -1 (VSMOW))
library(ggplot2)
p_Temp_min1 <- ggplot(data = wk_data, aes(x = meter, y = Temp_min1)) +
    theme_bw() +
    geom_point(color = "#8d58b8", shape = 2) + #add point data
    ylim((min(wk_data$Temp_min1)-0.01), (max(wk_data$Temp_min1)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
  
    geom_smooth(color = "#463c82", fill = "#c1bae8") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "Temperature (deg C)", 
         x = "meter", 
         title = "Temperature Plots",
         caption = "K-Pg Boundary at 0 m") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
    

plot(p_Temp_min1)


setwd(paste0(wd, "/Figures"))
ggsave("p_Temp_min1.png", width = 10, height = 6)
setwd(wd)
```

```{r}
#Temp by meter and aligned to SMdO

#plot Temp given water d18O value = 0 (VSMOW)
library(ggplot2)
p_Temp_meter <- ggplot(data = wk_data, aes(x = meter, y = Temp_min1)) +
    theme_bw() +
    geom_point(color = "#8d58b8", shape = 2) + #add point data
    ylim((min(wk_data$Temp_min1)-0.01), (max(wk_data$Temp_min1)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
    #scale_x_reverse() +
  
    geom_smooth(color = "#463c82", fill = "#c1bae8") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "Temperature (deg C)", 
         x = "meter", 
         title = "Temperature Plots (meter)",
         caption = "K-Pg Boundary at 0 m; Assumed seawater d18O = -1 (VSMOW)") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
plot(p_Temp_meter)


setwd(paste0(wd, "/Figures"))
ggsave("p_Temp_bymeter.png", width = 8, height = 6)
setwd(wd)

#plot Temperature aligned to age rather than meter
mydata <- all_sect %>% filter(
  Section %in% c(unique(wk_data$Section))
)
#add column to data with VSMOW d18O (from VPDB)
mydata$d18O_VSMOW <- to_VSMOW(mydata$d18O)
H2O_VSMOW <- to_VSMOW(0)
#add column calculating temps (deg C)
mydata$Temp_min1 <- temp_d18O(mydata$d18O_VSMOW, -1, "calcite", "ONeil69")

```

```{r}
library(ggplot2)
p_Temp_age <- ggplot(data = mydata, aes(x = Age, y = Temp_min1)) +
    theme_bw() +
    geom_point(color = "#8d58b8", shape = 2) + #add point data
    ylim((min(wk_data$Temp_min1)-0.01), (max(wk_data$Temp_min1)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
    scale_x_reverse() +
  
    geom_smooth(color = "#463c82", fill = "#c1bae8") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 66.052), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "Temperature (deg C)", 
         x = "Age", 
         title = "Temperature Plots (Absolute Age)",
         caption = "K-Pg Boundary at 0 m, Seawater assumed d18O = -1 per mil") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
    

plot(p_Temp_age)


setwd(paste0(wd, "/Figures"))
ggsave("p_Temp_AlignedSMdO.png", width = 8, height = 6)
setwd(wd)
```

```{r}
#d13C plottted with age
thisdata <- mydata %>% filter(
    Age <= 66.052
)
library(ggplot2)
p_C_age <- ggplot(data = thisdata, aes(x = Age, y = d13C)) +
    theme_bw() +
    geom_point(color = "#4b8c3c", shape = 2) + #add point data
    ylim((min(thisdata$d13C)-0.01), (max(thisdata$d13C)+0.01)) + #set axis limits to just larger than data values
  
    coord_flip() + #flip x and y so that meter is vertical
    scale_x_reverse() +
  
    geom_smooth(color = "#17400d", fill = "#aecca7") + #add smoothed loess fit
  

  
    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 66.052), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "Bulk d13C (per mil)", 
         x = "Age", 
         title = "Bulk Sample d13C Plots (Absolute Age)",
         caption = "K-Pg Boundary at 66.052 Ma") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots
    
    

plot(p_C_age)


setwd(paste0(wd, "/Figures"))
ggsave("p_d13C_age.png", width = 8, height = 6)
setwd(wd)
```

```{r}
#plot d13C and d18O together
p_CO <- ggplot(data = wk_data) +
    theme_bw() +
  #plot d13C
    geom_point(aes(x = meter, y = d13C), color = "#6e1a37", shape = 2) + #add point data
    geom_smooth(aes(x = meter, y = d13C), color = "#6e1a37", fill = "#d75656") + #add smoothed loess fit
  
  #plot d18O
    geom_point(aes(x = meter, y = d18O), color = "#021a54", shape = 2) + #add point data
    geom_smooth(aes(x = meter, y = d18O), color = "#021a54", fill = "#b1c7de") + #add smoothed loess fit
  
    coord_flip() + #flip x and y so that meter is vertical

    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 0), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "per mil", 
         x = "meter", 
         title = "d13C and d18OPlots",
         caption = "K-Pg Boundary at 0 m") + #add axis labels
  
    facet_grid(. ~ Section)  #break up into section plots

plot(p_CO)
setwd(paste0(wd, "/Figures"))
ggsave("p_CO.png", width = 10, height = 6)
setwd(wd)
```

#Plots with biozone markers
```{r, eval=FALSE}
library(patchwork)
#separate plot of biozones
biozones_TCC <- data.frame(c(unique(PG_TCC$Biozone)))
biozones_TCC <- biozones_TCC %>% rename("Biozone" = colnames(biozones_TCC[1]))
biozones_TCC$min <- 


bioz <- ggplot(PG_TCC) +  
  geom_rect(aes(
    xmin = 0, xmax = 1,
    ymin = min(meter), ymax = max(meter),
    fill = Biozone
  )) +
  scale_y_reverse() +
  theme_void() +
  theme(legend.position = "none")

p2 + p1 + plot_layout(widths = c(1, 4))
```


## By Distance
```{r, fig.width=8}
data <- all_sect #using all data to show differences by distance
library(terra)
library(dplyr)

crater <- rbind(c(-89.5, 21.4))
data <- data %>% mutate(
  Distance = signif((terra::distance(x = as.matrix(data[,c(6,5)]), y = crater,
                             lonlat = TRUE))/1000, 
                   digits = 1)
)
data <- data %>% mutate(
  Distance_f = paste0(as.character(Distance), " km")
)
#data$Distance_f = factor(data$Distance, levels=c())


p_dist <- ggplot(data = data) +
    theme_bw() +
  #plot d13C
    geom_point(aes(x = Age, y = d13C), color = "#6e1a37", shape = 2) + #add point data
    #geom_smooth(aes(x = meter, y = d13C), color = "#6e1a37", fill = "#d75656") + #add smoothed loess fit
  
  #plot d18O
    #geom_point(aes(x = Age, y = d18O), color = "#021a54", shape = 2) + #add point data
    #geom_smooth(aes(x = meter, y = d18O), color = "#021a54", fill = "#b1c7de") + #add smoothed loess fit
  
    coord_flip() + #flip x and y so that meter is vertical
  
    scale_x_reverse(limits = c(67, 65)) +

    geom_hline(aes(yintercept = 0)) + #add vertical line at d13C = 0
  
    geom_vline(aes(xintercept = 66.052), color = "#994b6b") + #add horizontal line at K-Pg boundary
  
    labs(y = "per mil", 
         x = "Age (Ma)", 
         title = "d13C By Distance from Impact Site",
         caption = "K-Pg Boundary at 66.052 Ma") + #add axis labels
  
    facet_grid(. ~ Distance_f)  #break up into section plots

plot(p_dist)
setwd(paste0(wd, "/Figures"))
ggsave("p_dist.png", width = 8, height = 5.5)
setwd(wd)
```

